-- DROP SEQUENCE --
DROP SEQUENCE S_NO_SEQ;
DROP SEQUENCE AD_NO_SEQ;
DROP SEQUENCE C_NO_SEQ;
DROP SEQUENCE MB_NO_SEQ;


-- DROP TABLE --
DROP TABLE MONEYBOOK CASCADE CONSTRAINTS; 
DROP TABLE CARD CASCADE CONSTRAINTS; 
DROP TABLE ADDRESSBOOK CASCADE CONSTRAINTS; 
DROP TABLE SCHEDULER CASCADE CONSTRAINTS; 
DROP TABLE MEMBER CASCADE CONSTRAINTS; 
